dist: trusty
sudo: required
language: csharp
mono: none
install:
  - sudo apt-get install dotnet-dev-1.0.0-preview3-004056
script:
  - dotnet restore
  - dotnet build --configuration Debug ./EFSqlTranslator.Translation ./EFSqlTranslator.ConsoleApp ./EFSqlTranslator.EFModels ./EFSqlTranslator.Tests
  - dotnet test ./EFSqlTranslator.Tests
